///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AllUsersModelData {
/*
{
  "users_id": 10,
  "first_name": "sri",
  "last_name": "ddf",
  "profile_pic": "df",
  "country": "df",
  "usdt_address": "df",
  "email": "df",
  "password": "df",
  "ticket_count": 0,
  "last_online": "2022-09-11T14:08:12.000Z",
  "createdAt": "2022-09-11T14:08:12.000Z",
  "updatedAt": null
} 
*/

  int? usersId;
  String? firstName;
  String? lastName;
  String? profilePic;
  String? country;
  String? usdtAddress;
  String? email;
  String? password;
  int? ticketCount;
  String? lastOnline;
  String? createdAt;
  String? updatedAt;

  AllUsersModelData({
    this.usersId,
    this.firstName,
    this.lastName,
    this.profilePic,
    this.country,
    this.usdtAddress,
    this.email,
    this.password,
    this.ticketCount,
    this.lastOnline,
    this.createdAt,
    this.updatedAt,
  });
  AllUsersModelData.fromJson(Map<String, dynamic> json) {
    usersId = json['users_id']?.toInt();
    firstName = json['first_name']?.toString();
    lastName = json['last_name']?.toString();
    profilePic = json['profile_pic']?.toString();
    country = json['country']?.toString();
    usdtAddress = json['usdt_address']?.toString();
    email = json['email']?.toString();
    password = json['password']?.toString();
    ticketCount = json['ticket_count']?.toInt();
    lastOnline = json['last_online']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['users_id'] = usersId;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['profile_pic'] = profilePic;
    data['country'] = country;
    data['usdt_address'] = usdtAddress;
    data['email'] = email;
    data['password'] = password;
    data['ticket_count'] = ticketCount;
    data['last_online'] = lastOnline;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class AllUsersModel {
/*
{
  "data": [
    {
      "users_id": 10,
      "first_name": "sri",
      "last_name": "ddf",
      "profile_pic": "df",
      "country": "df",
      "usdt_address": "df",
      "email": "df",
      "password": "df",
      "ticket_count": 0,
      "last_online": "2022-09-11T14:08:12.000Z",
      "createdAt": "2022-09-11T14:08:12.000Z",
      "updatedAt": null
    }
  ]
} 
*/

  List<AllUsersModelData?>? data;

  AllUsersModel({
    this.data,
  });
  AllUsersModel.fromJson(Map<String, dynamic> json) {
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <AllUsersModelData>[];
  v.forEach((v) {
  arr0.add(AllUsersModelData.fromJson(v));
  });
    this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data'] = arr0;
    }
    return data;
  }
}
