///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ApiKeyModel {
/*
{
  "api_id": 1,
  "api_key": "fdf",
  "createdAt": null,
  "updatedAt": null
} 
*/

  int? apiId;
  String? apiKey;
  String? createdAt;
  String? updatedAt;

  ApiKeyModel({
    this.apiId,
    this.apiKey,
    this.createdAt,
    this.updatedAt,
  });
  ApiKeyModel.fromJson(Map<String, dynamic> json) {
    apiId = json['api_id']?.toInt();
    apiKey = json['api_key']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['api_id'] = apiId;
    data['api_key'] = apiKey;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

ApiKeyModel? apikey;
