///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ChatModelData {
/*
{
  "chat_id": 1,
  "users_id": 3,
  "msg": "sssdsd",
  "is_sender": 1,
  "createdAt": "2022-09-10T10:41:43.000Z",
  "updatedAt": "2022-09-10T10:41:43.000Z"
} 
*/

  int? chatId;
  int? usersId;
  String? msg;
  int? isSender;
  String? createdAt;
  String? updatedAt;

  ChatModelData({
    this.chatId,
    this.usersId,
    this.msg,
    this.isSender,
    this.createdAt,
    this.updatedAt,
  });
  ChatModelData.fromJson(Map<String, dynamic> json) {
    chatId = json['chat_id']?.toInt();
    usersId = json['users_id']?.toInt();
    msg = json['msg']?.toString();
    isSender = json['is_sender']?.toInt();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['chat_id'] = chatId;
    data['users_id'] = usersId;
    data['msg'] = msg;
    data['is_sender'] = isSender;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class ChatModel {
/*
{
  "data": [
    {
      "chat_id": 1,
      "users_id": 3,
      "msg": "sssdsd",
      "is_sender": 1,
      "createdAt": "2022-09-10T10:41:43.000Z",
      "updatedAt": "2022-09-10T10:41:43.000Z"
    }
  ]
} 
*/

  List<ChatModelData?>? data;

  ChatModel({
    this.data,
  });
  ChatModel.fromJson(Map<String, dynamic> json) {
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <ChatModelData>[];
  v.forEach((v) {
  arr0.add(ChatModelData.fromJson(v));
  });
    this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data'] = arr0;
    }
    return data;
  }
}
