///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetLastRound {
/*
{
  "round_id": 3,
  "round_no": 3,
  "price": "4000",
  "start_at": "2022-08-27T08:25:01.000Z",
  "end_at": "2022-08-28T03:30:00.000Z",
  "createdAt": "2022-08-27T08:25:01.000Z",
  "updatedAt": "2022-08-27T08:25:01.000Z"
} 
*/

  int? roundId;
  int? roundNo;
  String? price;
  String? startAt;
  String? endAt;
  String? createdAt;
  String? updatedAt;

  GetLastRound({
    this.roundId,
    this.roundNo,
    this.price,
    this.startAt,
    this.endAt,
    this.createdAt,
    this.updatedAt,
  });
  GetLastRound.fromJson(Map<String, dynamic> json) {
    roundId = json['round_id']?.toInt();
    roundNo = json['round_no']?.toInt();
    price = json['price']?.toString();
    startAt = json['start_at']?.toString();
    endAt = json['end_at']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['round_id'] = roundId;
    data['round_no'] = roundNo;
    data['price'] = price;
    data['start_at'] = startAt;
    data['end_at'] = endAt;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}
