///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ShowPaymentModelDataTimeline {
/*
{
  "status": "NEW",
  "time": "2022-08-13T14:24:56Z"
} 
*/

  String? status;
  String? time;

  ShowPaymentModelDataTimeline({
    this.status,
    this.time,
  });
  ShowPaymentModelDataTimeline.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    time = json['time']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['time'] = time;
    return data;
  }
}

class ShowPaymentModelDataPricingBitcoin {
/*
{
  "amount": "0.00016324",
  "currency": "BTC"
} 
*/

  String? amount;
  String? currency;

  ShowPaymentModelDataPricingBitcoin({
    this.amount,
    this.currency,
  });
  ShowPaymentModelDataPricingBitcoin.fromJson(Map<String, dynamic> json) {
    amount = json['amount']?.toString();
    currency = json['currency']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['amount'] = amount;
    data['currency'] = currency;
    return data;
  }
}

class ShowPaymentModelDataPricingLitecoin {
/*
{
  "amount": "0.06231500",
  "currency": "LTC"
} 
*/

  String? amount;
  String? currency;

  ShowPaymentModelDataPricingLitecoin({
    this.amount,
    this.currency,
  });
  ShowPaymentModelDataPricingLitecoin.fromJson(Map<String, dynamic> json) {
    amount = json['amount']?.toString();
    currency = json['currency']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['amount'] = amount;
    data['currency'] = currency;
    return data;
  }
}

class ShowPaymentModelDataPricingDogecoin {
/*
{
  "amount": "54.52934360",
  "currency": "DOGE"
} 
*/

  String? amount;
  String? currency;

  ShowPaymentModelDataPricingDogecoin({
    this.amount,
    this.currency,
  });
  ShowPaymentModelDataPricingDogecoin.fromJson(Map<String, dynamic> json) {
    amount = json['amount']?.toString();
    currency = json['currency']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['amount'] = amount;
    data['currency'] = currency;
    return data;
  }
}

class ShowPaymentModelDataPricingBitcoincash {
/*
{
  "amount": "0.02768166",
  "currency": "BCH"
} 
*/

  String? amount;
  String? currency;

  ShowPaymentModelDataPricingBitcoincash({
    this.amount,
    this.currency,
  });
  ShowPaymentModelDataPricingBitcoincash.fromJson(Map<String, dynamic> json) {
    amount = json['amount']?.toString();
    currency = json['currency']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['amount'] = amount;
    data['currency'] = currency;
    return data;
  }
}

class ShowPaymentModelDataPricingTether {
/*
{
  "amount": "3.998421",
  "currency": "USDT"
} 
*/

  String? amount;
  String? currency;

  ShowPaymentModelDataPricingTether({
    this.amount,
    this.currency,
  });
  ShowPaymentModelDataPricingTether.fromJson(Map<String, dynamic> json) {
    amount = json['amount']?.toString();
    currency = json['currency']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['amount'] = amount;
    data['currency'] = currency;
    return data;
  }
}

class ShowPaymentModelDataPricingShibainu {
/*
{
  "amount": "316330.565440884000000000",
  "currency": "SHIB"
} 
*/

  String? amount;
  String? currency;

  ShowPaymentModelDataPricingShibainu({
    this.amount,
    this.currency,
  });
  ShowPaymentModelDataPricingShibainu.fromJson(Map<String, dynamic> json) {
    amount = json['amount']?.toString();
    currency = json['currency']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['amount'] = amount;
    data['currency'] = currency;
    return data;
  }
}

class ShowPaymentModelDataPricingApecoin {
/*
{
  "amount": "0.581987487269023716",
  "currency": "APE"
} 
*/

  String? amount;
  String? currency;

  ShowPaymentModelDataPricingApecoin({
    this.amount,
    this.currency,
  });
  ShowPaymentModelDataPricingApecoin.fromJson(Map<String, dynamic> json) {
    amount = json['amount']?.toString();
    currency = json['currency']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['amount'] = amount;
    data['currency'] = currency;
    return data;
  }
}

class ShowPaymentModelDataPricingDai {
/*
{
  "amount": "4.000400040000000000",
  "currency": "DAI"
} 
*/

  String? amount;
  String? currency;

  ShowPaymentModelDataPricingDai({
    this.amount,
    this.currency,
  });
  ShowPaymentModelDataPricingDai.fromJson(Map<String, dynamic> json) {
    amount = json['amount']?.toString();
    currency = json['currency']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['amount'] = amount;
    data['currency'] = currency;
    return data;
  }
}

class ShowPaymentModelDataPricingUsdc {
/*
{
  "amount": "4.000000",
  "currency": "USDC"
} 
*/

  String? amount;
  String? currency;

  ShowPaymentModelDataPricingUsdc({
    this.amount,
    this.currency,
  });
  ShowPaymentModelDataPricingUsdc.fromJson(Map<String, dynamic> json) {
    amount = json['amount']?.toString();
    currency = json['currency']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['amount'] = amount;
    data['currency'] = currency;
    return data;
  }
}

class ShowPaymentModelDataPricingEthereum {
/*
{
  "amount": "0.002017000",
  "currency": "ETH"
} 
*/

  String? amount;
  String? currency;

  ShowPaymentModelDataPricingEthereum({
    this.amount,
    this.currency,
  });
  ShowPaymentModelDataPricingEthereum.fromJson(Map<String, dynamic> json) {
    amount = json['amount']?.toString();
    currency = json['currency']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['amount'] = amount;
    data['currency'] = currency;
    return data;
  }
}

class ShowPaymentModelDataPricingLocal {
/*
{
  "amount": "4.00",
  "currency": "USD"
} 
*/

  String? amount;
  String? currency;

  ShowPaymentModelDataPricingLocal({
    this.amount,
    this.currency,
  });
  ShowPaymentModelDataPricingLocal.fromJson(Map<String, dynamic> json) {
    amount = json['amount']?.toString();
    currency = json['currency']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['amount'] = amount;
    data['currency'] = currency;
    return data;
  }
}

class ShowPaymentModelDataPricing {
/*
{
  "local": {
    "amount": "4.00",
    "currency": "USD"
  },
  "ethereum": {
    "amount": "0.002017000",
    "currency": "ETH"
  },
  "usdc": {
    "amount": "4.000000",
    "currency": "USDC"
  },
  "dai": {
    "amount": "4.000400040000000000",
    "currency": "DAI"
  },
  "apecoin": {
    "amount": "0.581987487269023716",
    "currency": "APE"
  },
  "shibainu": {
    "amount": "316330.565440884000000000",
    "currency": "SHIB"
  },
  "tether": {
    "amount": "3.998421",
    "currency": "USDT"
  },
  "bitcoincash": {
    "amount": "0.02768166",
    "currency": "BCH"
  },
  "dogecoin": {
    "amount": "54.52934360",
    "currency": "DOGE"
  },
  "litecoin": {
    "amount": "0.06231500",
    "currency": "LTC"
  },
  "bitcoin": {
    "amount": "0.00016324",
    "currency": "BTC"
  }
} 
*/

  ShowPaymentModelDataPricingLocal? local;
  ShowPaymentModelDataPricingEthereum? ethereum;
  ShowPaymentModelDataPricingUsdc? usdc;
  ShowPaymentModelDataPricingDai? dai;
  ShowPaymentModelDataPricingApecoin? apecoin;
  ShowPaymentModelDataPricingShibainu? shibainu;
  ShowPaymentModelDataPricingTether? tether;
  ShowPaymentModelDataPricingBitcoincash? bitcoincash;
  ShowPaymentModelDataPricingDogecoin? dogecoin;
  ShowPaymentModelDataPricingLitecoin? litecoin;
  ShowPaymentModelDataPricingBitcoin? bitcoin;

  ShowPaymentModelDataPricing({
    this.local,
    this.ethereum,
    this.usdc,
    this.dai,
    this.apecoin,
    this.shibainu,
    this.tether,
    this.bitcoincash,
    this.dogecoin,
    this.litecoin,
    this.bitcoin,
  });
  ShowPaymentModelDataPricing.fromJson(Map<String, dynamic> json) {
    local = (json['local'] != null) ? ShowPaymentModelDataPricingLocal.fromJson(json['local']) : null;
    ethereum = (json['ethereum'] != null) ? ShowPaymentModelDataPricingEthereum.fromJson(json['ethereum']) : null;
    usdc = (json['usdc'] != null) ? ShowPaymentModelDataPricingUsdc.fromJson(json['usdc']) : null;
    dai = (json['dai'] != null) ? ShowPaymentModelDataPricingDai.fromJson(json['dai']) : null;
    apecoin = (json['apecoin'] != null) ? ShowPaymentModelDataPricingApecoin.fromJson(json['apecoin']) : null;
    shibainu = (json['shibainu'] != null) ? ShowPaymentModelDataPricingShibainu.fromJson(json['shibainu']) : null;
    tether = (json['tether'] != null) ? ShowPaymentModelDataPricingTether.fromJson(json['tether']) : null;
    bitcoincash = (json['bitcoincash'] != null) ? ShowPaymentModelDataPricingBitcoincash.fromJson(json['bitcoincash']) : null;
    dogecoin = (json['dogecoin'] != null) ? ShowPaymentModelDataPricingDogecoin.fromJson(json['dogecoin']) : null;
    litecoin = (json['litecoin'] != null) ? ShowPaymentModelDataPricingLitecoin.fromJson(json['litecoin']) : null;
    bitcoin = (json['bitcoin'] != null) ? ShowPaymentModelDataPricingBitcoin.fromJson(json['bitcoin']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (local != null) {
      data['local'] = local!.toJson();
    }
    if (ethereum != null) {
      data['ethereum'] = ethereum!.toJson();
    }
    if (usdc != null) {
      data['usdc'] = usdc!.toJson();
    }
    if (dai != null) {
      data['dai'] = dai!.toJson();
    }
    if (apecoin != null) {
      data['apecoin'] = apecoin!.toJson();
    }
    if (shibainu != null) {
      data['shibainu'] = shibainu!.toJson();
    }
    if (tether != null) {
      data['tether'] = tether!.toJson();
    }
    if (bitcoincash != null) {
      data['bitcoincash'] = bitcoincash!.toJson();
    }
    if (dogecoin != null) {
      data['dogecoin'] = dogecoin!.toJson();
    }
    if (litecoin != null) {
      data['litecoin'] = litecoin!.toJson();
    }
    if (bitcoin != null) {
      data['bitcoin'] = bitcoin!.toJson();
    }
    return data;
  }
}

class ShowPaymentModelDataPaymentThresholdUnderpaymentAbsoluteThreshold {
/*
{
  "amount": "5.00",
  "currency": "USD"
} 
*/

  String? amount;
  String? currency;

  ShowPaymentModelDataPaymentThresholdUnderpaymentAbsoluteThreshold({
    this.amount,
    this.currency,
  });
  ShowPaymentModelDataPaymentThresholdUnderpaymentAbsoluteThreshold.fromJson(Map<String, dynamic> json) {
    amount = json['amount']?.toString();
    currency = json['currency']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['amount'] = amount;
    data['currency'] = currency;
    return data;
  }
}

class ShowPaymentModelDataPaymentThresholdOverpaymentAbsoluteThreshold {
/*
{
  "amount": "5.00",
  "currency": "USD"
} 
*/

  String? amount;
  String? currency;

  ShowPaymentModelDataPaymentThresholdOverpaymentAbsoluteThreshold({
    this.amount,
    this.currency,
  });
  ShowPaymentModelDataPaymentThresholdOverpaymentAbsoluteThreshold.fromJson(Map<String, dynamic> json) {
    amount = json['amount']?.toString();
    currency = json['currency']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['amount'] = amount;
    data['currency'] = currency;
    return data;
  }
}

class ShowPaymentModelDataPaymentThreshold {
/*
{
  "overpayment_absolute_threshold": {
    "amount": "5.00",
    "currency": "USD"
  },
  "overpayment_relative_threshold": "0.005",
  "underpayment_absolute_threshold": {
    "amount": "5.00",
    "currency": "USD"
  },
  "underpayment_relative_threshold": "0.005"
} 
*/

  ShowPaymentModelDataPaymentThresholdOverpaymentAbsoluteThreshold? overpaymentAbsoluteThreshold;
  String? overpaymentRelativeThreshold;
  ShowPaymentModelDataPaymentThresholdUnderpaymentAbsoluteThreshold? underpaymentAbsoluteThreshold;
  String? underpaymentRelativeThreshold;

  ShowPaymentModelDataPaymentThreshold({
    this.overpaymentAbsoluteThreshold,
    this.overpaymentRelativeThreshold,
    this.underpaymentAbsoluteThreshold,
    this.underpaymentRelativeThreshold,
  });
  ShowPaymentModelDataPaymentThreshold.fromJson(Map<String, dynamic> json) {
    overpaymentAbsoluteThreshold = (json['overpayment_absolute_threshold'] != null) ? ShowPaymentModelDataPaymentThresholdOverpaymentAbsoluteThreshold.fromJson(json['overpayment_absolute_threshold']) : null;
    overpaymentRelativeThreshold = json['overpayment_relative_threshold']?.toString();
    underpaymentAbsoluteThreshold = (json['underpayment_absolute_threshold'] != null) ? ShowPaymentModelDataPaymentThresholdUnderpaymentAbsoluteThreshold.fromJson(json['underpayment_absolute_threshold']) : null;
    underpaymentRelativeThreshold = json['underpayment_relative_threshold']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (overpaymentAbsoluteThreshold != null) {
      data['overpayment_absolute_threshold'] = overpaymentAbsoluteThreshold!.toJson();
    }
    data['overpayment_relative_threshold'] = overpaymentRelativeThreshold;
    if (underpaymentAbsoluteThreshold != null) {
      data['underpayment_absolute_threshold'] = underpaymentAbsoluteThreshold!.toJson();
    }
    data['underpayment_relative_threshold'] = underpaymentRelativeThreshold;
    return data;
  }
}

class ShowPaymentModelDataLocalExchangeRates {
/*
{
  "APE-USD": "6.873",
  "BCH-USD": "144.5",
  "BTC-USD": "24503.93",
  "DAI-USD": "0.9999",
  "ETH-USD": "1983.455",
  "LTC-USD": "64.19",
  "DOGE-USD": "0.073355",
  "SHIB-USD": "0.000012645",
  "USDC-USD": "1.0",
  "USDT-USD": "1.000395"
} 
*/

  String? APEUSD;
  String? BCHUSD;
  String? BTCUSD;
  String? DAIUSD;
  String? ETHUSD;
  String? LTCUSD;
  String? DOGEUSD;
  String? SHIBUSD;
  String? USDCUSD;
  String? USDTUSD;

  ShowPaymentModelDataLocalExchangeRates({
    this.APEUSD,
    this.BCHUSD,
    this.BTCUSD,
    this.DAIUSD,
    this.ETHUSD,
    this.LTCUSD,
    this.DOGEUSD,
    this.SHIBUSD,
    this.USDCUSD,
    this.USDTUSD,
  });
  ShowPaymentModelDataLocalExchangeRates.fromJson(Map<String, dynamic> json) {
    APEUSD = json['APE-USD']?.toString();
    BCHUSD = json['BCH-USD']?.toString();
    BTCUSD = json['BTC-USD']?.toString();
    DAIUSD = json['DAI-USD']?.toString();
    ETHUSD = json['ETH-USD']?.toString();
    LTCUSD = json['LTC-USD']?.toString();
    DOGEUSD = json['DOGE-USD']?.toString();
    SHIBUSD = json['SHIB-USD']?.toString();
    USDCUSD = json['USDC-USD']?.toString();
    USDTUSD = json['USDT-USD']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['APE-USD'] = APEUSD;
    data['BCH-USD'] = BCHUSD;
    data['BTC-USD'] = BTCUSD;
    data['DAI-USD'] = DAIUSD;
    data['ETH-USD'] = ETHUSD;
    data['LTC-USD'] = LTCUSD;
    data['DOGE-USD'] = DOGEUSD;
    data['SHIB-USD'] = SHIBUSD;
    data['USDC-USD'] = USDCUSD;
    data['USDT-USD'] = USDTUSD;
    return data;
  }
}

class ShowPaymentModelDataExchangeRates {
/*
{
  "APE-USD": "6.873",
  "BCH-USD": "144.5",
  "BTC-USD": "24503.93",
  "DAI-USD": "0.9999",
  "ETH-USD": "1983.455",
  "LTC-USD": "64.19",
  "DOGE-USD": "0.073355",
  "SHIB-USD": "0.000012645",
  "USDC-USD": "1.0",
  "USDT-USD": "1.000395"
} 
*/

  String? APEUSD;
  String? BCHUSD;
  String? BTCUSD;
  String? DAIUSD;
  String? ETHUSD;
  String? LTCUSD;
  String? DOGEUSD;
  String? SHIBUSD;
  String? USDCUSD;
  String? USDTUSD;

  ShowPaymentModelDataExchangeRates({
    this.APEUSD,
    this.BCHUSD,
    this.BTCUSD,
    this.DAIUSD,
    this.ETHUSD,
    this.LTCUSD,
    this.DOGEUSD,
    this.SHIBUSD,
    this.USDCUSD,
    this.USDTUSD,
  });
  ShowPaymentModelDataExchangeRates.fromJson(Map<String, dynamic> json) {
    APEUSD = json['APE-USD']?.toString();
    BCHUSD = json['BCH-USD']?.toString();
    BTCUSD = json['BTC-USD']?.toString();
    DAIUSD = json['DAI-USD']?.toString();
    ETHUSD = json['ETH-USD']?.toString();
    LTCUSD = json['LTC-USD']?.toString();
    DOGEUSD = json['DOGE-USD']?.toString();
    SHIBUSD = json['SHIB-USD']?.toString();
    USDCUSD = json['USDC-USD']?.toString();
    USDTUSD = json['USDT-USD']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['APE-USD'] = APEUSD;
    data['BCH-USD'] = BCHUSD;
    data['BTC-USD'] = BTCUSD;
    data['DAI-USD'] = DAIUSD;
    data['ETH-USD'] = ETHUSD;
    data['LTC-USD'] = LTCUSD;
    data['DOGE-USD'] = DOGEUSD;
    data['SHIB-USD'] = SHIBUSD;
    data['USDC-USD'] = USDCUSD;
    data['USDT-USD'] = USDTUSD;
    return data;
  }
}

class ShowPaymentModelDataAddresses {
/*
{
  "ethereum": "0xc107683b2c9899858fc859c1c61fe852dda05fa2",
  "usdc": "0xc107683b2c9899858fc859c1c61fe852dda05fa2",
  "dai": "0xc107683b2c9899858fc859c1c61fe852dda05fa2",
  "apecoin": "0xc107683b2c9899858fc859c1c61fe852dda05fa2",
  "shibainu": "0xc107683b2c9899858fc859c1c61fe852dda05fa2",
  "tether": "0xc107683b2c9899858fc859c1c61fe852dda05fa2",
  "bitcoincash": "qquq0m8rq5m2e6h953jznl8z8q4c39p4ms9yl44yjd",
  "dogecoin": "D8YzRkWmn6Hk1gS3SsaWGLfXjWHwPVQgmY",
  "litecoin": "MMpGSFa8FMbt4URN3QcXQduVcvjM3YxB1w",
  "bitcoin": "3BE71PPub9XCrhbLRm9AaNDPySgczJdCju"
} 
*/

  String? ethereum;
  String? usdc;
  String? dai;
  String? apecoin;
  String? shibainu;
  String? tether;
  String? bitcoincash;
  String? dogecoin;
  String? litecoin;
  String? bitcoin;

  ShowPaymentModelDataAddresses({
    this.ethereum,
    this.usdc,
    this.dai,
    this.apecoin,
    this.shibainu,
    this.tether,
    this.bitcoincash,
    this.dogecoin,
    this.litecoin,
    this.bitcoin,
  });
  ShowPaymentModelDataAddresses.fromJson(Map<String, dynamic> json) {
    ethereum = json['ethereum']?.toString();
    usdc = json['usdc']?.toString();
    dai = json['dai']?.toString();
    apecoin = json['apecoin']?.toString();
    shibainu = json['shibainu']?.toString();
    tether = json['tether']?.toString();
    bitcoincash = json['bitcoincash']?.toString();
    dogecoin = json['dogecoin']?.toString();
    litecoin = json['litecoin']?.toString();
    bitcoin = json['bitcoin']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ethereum'] = ethereum;
    data['usdc'] = usdc;
    data['dai'] = dai;
    data['apecoin'] = apecoin;
    data['shibainu'] = shibainu;
    data['tether'] = tether;
    data['bitcoincash'] = bitcoincash;
    data['dogecoin'] = dogecoin;
    data['litecoin'] = litecoin;
    data['bitcoin'] = bitcoin;
    return data;
  }
}

class ShowPaymentModelData {
/*
{
  "addresses": {
    "ethereum": "0xc107683b2c9899858fc859c1c61fe852dda05fa2",
    "usdc": "0xc107683b2c9899858fc859c1c61fe852dda05fa2",
    "dai": "0xc107683b2c9899858fc859c1c61fe852dda05fa2",
    "apecoin": "0xc107683b2c9899858fc859c1c61fe852dda05fa2",
    "shibainu": "0xc107683b2c9899858fc859c1c61fe852dda05fa2",
    "tether": "0xc107683b2c9899858fc859c1c61fe852dda05fa2",
    "bitcoincash": "qquq0m8rq5m2e6h953jznl8z8q4c39p4ms9yl44yjd",
    "dogecoin": "D8YzRkWmn6Hk1gS3SsaWGLfXjWHwPVQgmY",
    "litecoin": "MMpGSFa8FMbt4URN3QcXQduVcvjM3YxB1w",
    "bitcoin": "3BE71PPub9XCrhbLRm9AaNDPySgczJdCju"
  },
  "brand_color": "#122332",
  "brand_logo_url": "",
  "cancel_url": "https://charge/canceled/page",
  "code": "RNGFQGBK",
  "created_at": "2022-08-13T14:24:56Z",
  "description": "Golden",
  "exchange_rates": {
    "APE-USD": "6.873",
    "BCH-USD": "144.5",
    "BTC-USD": "24503.93",
    "DAI-USD": "0.9999",
    "ETH-USD": "1983.455",
    "LTC-USD": "64.19",
    "DOGE-USD": "0.073355",
    "SHIB-USD": "0.000012645",
    "USDC-USD": "1.0",
    "USDT-USD": "1.000395"
  },
  "expires_at": "2022-08-13T15:24:56Z",
  "fee_rate": 0.01,
  "fees_settled": true,
  "hosted_url": "https://commerce.coinbase.com/charges/RNGFQGBK",
  "id": "308e89f7-3aa4-4198-b70c-e1873e91fdbc",
  "local_exchange_rates": {
    "APE-USD": "6.873",
    "BCH-USD": "144.5",
    "BTC-USD": "24503.93",
    "DAI-USD": "0.9999",
    "ETH-USD": "1983.455",
    "LTC-USD": "64.19",
    "DOGE-USD": "0.073355",
    "SHIB-USD": "0.000012645",
    "USDC-USD": "1.0",
    "USDT-USD": "1.000395"
  },
  "logo_url": "",
  "name": "156862",
  "offchain_eligible": false,
  "organization_name": "",
  "payment_threshold": {
    "overpayment_absolute_threshold": {
      "amount": "5.00",
      "currency": "USD"
    },
    "overpayment_relative_threshold": "0.005",
    "underpayment_absolute_threshold": {
      "amount": "5.00",
      "currency": "USD"
    },
    "underpayment_relative_threshold": "0.005"
  },
  "pricing": {
    "local": {
      "amount": "4.00",
      "currency": "USD"
    },
    "ethereum": {
      "amount": "0.002017000",
      "currency": "ETH"
    },
    "usdc": {
      "amount": "4.000000",
      "currency": "USDC"
    },
    "dai": {
      "amount": "4.000400040000000000",
      "currency": "DAI"
    },
    "apecoin": {
      "amount": "0.581987487269023716",
      "currency": "APE"
    },
    "shibainu": {
      "amount": "316330.565440884000000000",
      "currency": "SHIB"
    },
    "tether": {
      "amount": "3.998421",
      "currency": "USDT"
    },
    "bitcoincash": {
      "amount": "0.02768166",
      "currency": "BCH"
    },
    "dogecoin": {
      "amount": "54.52934360",
      "currency": "DOGE"
    },
    "litecoin": {
      "amount": "0.06231500",
      "currency": "LTC"
    },
    "bitcoin": {
      "amount": "0.00016324",
      "currency": "BTC"
    }
  },
  "pricing_type": "fixed_price",
  "pwcb_only": false,
  "redirect_url": "https://charge/completed/page",
  "resource": "charge",
  "support_email": "dan.malshan@gmail.com",
  "timeline": [
    {
      "status": "NEW",
      "time": "2022-08-13T14:24:56Z"
    }
  ],
  "utxo": false
} 
*/

  ShowPaymentModelDataAddresses? addresses;
  String? brandColor;
  String? brandLogoUrl;
  String? cancelUrl;
  String? code;
  String? createdAt;
  String? description;
  ShowPaymentModelDataExchangeRates? exchangeRates;
  String? expiresAt;
  double? feeRate;
  bool? feesSettled;
  String? hostedUrl;
  String? id;
  ShowPaymentModelDataLocalExchangeRates? localExchangeRates;
  String? logoUrl;
  String? name;
  bool? offchainEligible;
  String? organizationName;
  ShowPaymentModelDataPaymentThreshold? paymentThreshold;
  ShowPaymentModelDataPricing? pricing;
  String? pricingType;
  bool? pwcbOnly;
  String? redirectUrl;
  String? resource;
  String? supportEmail;
  List<ShowPaymentModelDataTimeline?>? timeline;
  bool? utxo;

  ShowPaymentModelData({
    this.addresses,
    this.brandColor,
    this.brandLogoUrl,
    this.cancelUrl,
    this.code,
    this.createdAt,
    this.description,
    this.exchangeRates,
    this.expiresAt,
    this.feeRate,
    this.feesSettled,
    this.hostedUrl,
    this.id,
    this.localExchangeRates,
    this.logoUrl,
    this.name,
    this.offchainEligible,
    this.organizationName,
    this.paymentThreshold,
    this.pricing,
    this.pricingType,
    this.pwcbOnly,
    this.redirectUrl,
    this.resource,
    this.supportEmail,
    this.timeline,
    this.utxo,
  });
  ShowPaymentModelData.fromJson(Map<String, dynamic> json) {
    addresses = (json['addresses'] != null) ? ShowPaymentModelDataAddresses.fromJson(json['addresses']) : null;
    brandColor = json['brand_color']?.toString();
    brandLogoUrl = json['brand_logo_url']?.toString();
    cancelUrl = json['cancel_url']?.toString();
    code = json['code']?.toString();
    createdAt = json['created_at']?.toString();
    description = json['description']?.toString();
    exchangeRates = (json['exchange_rates'] != null) ? ShowPaymentModelDataExchangeRates.fromJson(json['exchange_rates']) : null;
    expiresAt = json['expires_at']?.toString();
    feeRate = json['fee_rate']?.toDouble();
    feesSettled = json['fees_settled'];
    hostedUrl = json['hosted_url']?.toString();
    id = json['id']?.toString();
    localExchangeRates = (json['local_exchange_rates'] != null) ? ShowPaymentModelDataLocalExchangeRates.fromJson(json['local_exchange_rates']) : null;
    logoUrl = json['logo_url']?.toString();
    name = json['name']?.toString();
    offchainEligible = json['offchain_eligible'];
    organizationName = json['organization_name']?.toString();
    paymentThreshold = (json['payment_threshold'] != null) ? ShowPaymentModelDataPaymentThreshold.fromJson(json['payment_threshold']) : null;
    pricing = (json['pricing'] != null) ? ShowPaymentModelDataPricing.fromJson(json['pricing']) : null;
    pricingType = json['pricing_type']?.toString();
    pwcbOnly = json['pwcb_only'];
    redirectUrl = json['redirect_url']?.toString();
    resource = json['resource']?.toString();
    supportEmail = json['support_email']?.toString();
  if (json['timeline'] != null) {
  final v = json['timeline'];
  final arr0 = <ShowPaymentModelDataTimeline>[];
  v.forEach((v) {
  arr0.add(ShowPaymentModelDataTimeline.fromJson(v));
  });
    timeline = arr0;
    }
    utxo = json['utxo'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (addresses != null) {
      data['addresses'] = addresses!.toJson();
    }
    data['brand_color'] = brandColor;
    data['brand_logo_url'] = brandLogoUrl;
    data['cancel_url'] = cancelUrl;
    data['code'] = code;
    data['created_at'] = createdAt;
    data['description'] = description;
    if (exchangeRates != null) {
      data['exchange_rates'] = exchangeRates!.toJson();
    }
    data['expires_at'] = expiresAt;
    data['fee_rate'] = feeRate;
    data['fees_settled'] = feesSettled;
    data['hosted_url'] = hostedUrl;
    data['id'] = id;
    if (localExchangeRates != null) {
      data['local_exchange_rates'] = localExchangeRates!.toJson();
    }
    data['logo_url'] = logoUrl;
    data['name'] = name;
    data['offchain_eligible'] = offchainEligible;
    data['organization_name'] = organizationName;
    if (paymentThreshold != null) {
      data['payment_threshold'] = paymentThreshold!.toJson();
    }
    if (pricing != null) {
      data['pricing'] = pricing!.toJson();
    }
    data['pricing_type'] = pricingType;
    data['pwcb_only'] = pwcbOnly;
    data['redirect_url'] = redirectUrl;
    data['resource'] = resource;
    data['support_email'] = supportEmail;
    if (timeline != null) {
      final v = timeline;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['timeline'] = arr0;
    }
    data['utxo'] = utxo;
    return data;
  }
}

class ShowPaymentModel {
/*
{
  "data": {
    "addresses": {
      "ethereum": "0xc107683b2c9899858fc859c1c61fe852dda05fa2",
      "usdc": "0xc107683b2c9899858fc859c1c61fe852dda05fa2",
      "dai": "0xc107683b2c9899858fc859c1c61fe852dda05fa2",
      "apecoin": "0xc107683b2c9899858fc859c1c61fe852dda05fa2",
      "shibainu": "0xc107683b2c9899858fc859c1c61fe852dda05fa2",
      "tether": "0xc107683b2c9899858fc859c1c61fe852dda05fa2",
      "bitcoincash": "qquq0m8rq5m2e6h953jznl8z8q4c39p4ms9yl44yjd",
      "dogecoin": "D8YzRkWmn6Hk1gS3SsaWGLfXjWHwPVQgmY",
      "litecoin": "MMpGSFa8FMbt4URN3QcXQduVcvjM3YxB1w",
      "bitcoin": "3BE71PPub9XCrhbLRm9AaNDPySgczJdCju"
    },
    "brand_color": "#122332",
    "brand_logo_url": "",
    "cancel_url": "https://charge/canceled/page",
    "code": "RNGFQGBK",
    "created_at": "2022-08-13T14:24:56Z",
    "description": "Golden",
    "exchange_rates": {
      "APE-USD": "6.873",
      "BCH-USD": "144.5",
      "BTC-USD": "24503.93",
      "DAI-USD": "0.9999",
      "ETH-USD": "1983.455",
      "LTC-USD": "64.19",
      "DOGE-USD": "0.073355",
      "SHIB-USD": "0.000012645",
      "USDC-USD": "1.0",
      "USDT-USD": "1.000395"
    },
    "expires_at": "2022-08-13T15:24:56Z",
    "fee_rate": 0.01,
    "fees_settled": true,
    "hosted_url": "https://commerce.coinbase.com/charges/RNGFQGBK",
    "id": "308e89f7-3aa4-4198-b70c-e1873e91fdbc",
    "local_exchange_rates": {
      "APE-USD": "6.873",
      "BCH-USD": "144.5",
      "BTC-USD": "24503.93",
      "DAI-USD": "0.9999",
      "ETH-USD": "1983.455",
      "LTC-USD": "64.19",
      "DOGE-USD": "0.073355",
      "SHIB-USD": "0.000012645",
      "USDC-USD": "1.0",
      "USDT-USD": "1.000395"
    },
    "logo_url": "",
    "name": "156862",
    "offchain_eligible": false,
    "organization_name": "",
    "payment_threshold": {
      "overpayment_absolute_threshold": {
        "amount": "5.00",
        "currency": "USD"
      },
      "overpayment_relative_threshold": "0.005",
      "underpayment_absolute_threshold": {
        "amount": "5.00",
        "currency": "USD"
      },
      "underpayment_relative_threshold": "0.005"
    },
    "pricing": {
      "local": {
        "amount": "4.00",
        "currency": "USD"
      },
      "ethereum": {
        "amount": "0.002017000",
        "currency": "ETH"
      },
      "usdc": {
        "amount": "4.000000",
        "currency": "USDC"
      },
      "dai": {
        "amount": "4.000400040000000000",
        "currency": "DAI"
      },
      "apecoin": {
        "amount": "0.581987487269023716",
        "currency": "APE"
      },
      "shibainu": {
        "amount": "316330.565440884000000000",
        "currency": "SHIB"
      },
      "tether": {
        "amount": "3.998421",
        "currency": "USDT"
      },
      "bitcoincash": {
        "amount": "0.02768166",
        "currency": "BCH"
      },
      "dogecoin": {
        "amount": "54.52934360",
        "currency": "DOGE"
      },
      "litecoin": {
        "amount": "0.06231500",
        "currency": "LTC"
      },
      "bitcoin": {
        "amount": "0.00016324",
        "currency": "BTC"
      }
    },
    "pricing_type": "fixed_price",
    "pwcb_only": false,
    "redirect_url": "https://charge/completed/page",
    "resource": "charge",
    "support_email": "dan.malshan@gmail.com",
    "timeline": [
      {
        "status": "NEW",
        "time": "2022-08-13T14:24:56Z"
      }
    ],
    "utxo": false
  }
} 
*/

  ShowPaymentModelData? data;

  ShowPaymentModel({
    this.data,
  });
  ShowPaymentModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? ShowPaymentModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
