///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TicketModelData {
/*
{
  "ticket_id": 1,
  "ticket_number": "",
  "ticket_type": 0,
  "round_no": 1,
  "title": "ss",
  "price": 5,
  "start_date": "2022-10-29T15:57:36.000Z",
  "expire_date": "2022-10-29T03:30:00.000Z",
  "sold": 0,
  "createdAt": "2022-10-29T15:57:36.000Z",
  "updatedAt": "2022-10-29T15:57:36.000Z"
} 
*/

  int? ticketId;
  String? ticketNumber;
  int? ticketType;
  int? roundNo;
  String? title;
  int? price;
  String? startDate;
  String? expireDate;
  int? sold;
  String? createdAt;
  String? updatedAt;

  TicketModelData({
    this.ticketId,
    this.ticketNumber,
    this.ticketType,
    this.roundNo,
    this.title,
    this.price,
    this.startDate,
    this.expireDate,
    this.sold,
    this.createdAt,
    this.updatedAt,
  });
  TicketModelData.fromJson(Map<String, dynamic> json) {
    ticketId = json['ticket_id']?.toInt();
    ticketNumber = json['ticket_number']?.toString();
    ticketType = json['ticket_type']?.toInt();
    roundNo = json['round_no']?.toInt();
    title = json['title']?.toString();
    price = json['price']?.toInt();
    startDate = json['start_date']?.toString();
    expireDate = json['expire_date']?.toString();
    sold = json['sold']?.toInt();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['ticket_id'] = ticketId;
    data['ticket_number'] = ticketNumber;
    data['ticket_type'] = ticketType;
    data['round_no'] = roundNo;
    data['title'] = title;
    data['price'] = price;
    data['start_date'] = startDate;
    data['expire_date'] = expireDate;
    data['sold'] = sold;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class TicketModel {
/*
{
  "data": [
    {
      "ticket_id": 1,
      "ticket_number": "",
      "ticket_type": 0,
      "round_no": 1,
      "title": "ss",
      "price": 5,
      "start_date": "2022-10-29T15:57:36.000Z",
      "expire_date": "2022-10-29T03:30:00.000Z",
      "sold": 0,
      "createdAt": "2022-10-29T15:57:36.000Z",
      "updatedAt": "2022-10-29T15:57:36.000Z"
    }
  ]
} 
*/

  List<TicketModelData?>? data;

  TicketModel({
    this.data,
  });
  TicketModel.fromJson(Map<String, dynamic> json) {
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <TicketModelData>[];
  v.forEach((v) {
  arr0.add(TicketModelData.fromJson(v));
  });
    this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data'] = arr0;
    }
    return data;
  }
}
