///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserDetailsModel {
/*
{
  "users_id": 3,
  "first_name": "danu",
  "last_name": "malshan",
  "profile_pic": "",
  "country": "sri lanka",
  "usdt_address": "dfxddf",
  "email": "dan.malshan@gmail.com",
  "password": "$2a$08$FYiVDcuA6a7/4Ur8OHBD8e7fLQZGE0POhCbMS9KLHgyAP7sF.Tnie",
  "ticket_count": 4,
  "last_online": "2022-09-11T08:09:30.000Z",
  "is_admin": 0,
  "createdAt": "2022-08-03T16:33:12.000Z",
  "updatedAt": "2022-09-11T08:09:29.000Z",
  "dev_by": "D-Soft"
} 
*/

  int? usersId;
  String? firstName;
  String? lastName;
  String? profilePic;
  String? country;
  String? usdtAddress;
  String? email;
  String? password;
  int? ticketCount;
  String? lastOnline;
  int? isAdmin;
  String? createdAt;
  String? updatedAt;
  String? devBy;

  UserDetailsModel({
    this.usersId,
    this.firstName,
    this.lastName,
    this.profilePic,
    this.country,
    this.usdtAddress,
    this.email,
    this.password,
    this.ticketCount,
    this.lastOnline,
    this.isAdmin,
    this.createdAt,
    this.updatedAt,
    this.devBy,
  });
  UserDetailsModel.fromJson(Map<String, dynamic> json) {
    usersId = json['users_id']?.toInt();
    firstName = json['first_name']?.toString();
    lastName = json['last_name']?.toString();
    profilePic = json['profile_pic']?.toString();
    country = json['country']?.toString();
    usdtAddress = json['usdt_address']?.toString();
    email = json['email']?.toString();
    password = json['password']?.toString();
    ticketCount = json['ticket_count']?.toInt();
    lastOnline = json['last_online']?.toString();
    isAdmin = json['is_admin']?.toInt();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    devBy = json['dev_by']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['users_id'] = usersId;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['profile_pic'] = profilePic;
    data['country'] = country;
    data['usdt_address'] = usdtAddress;
    data['email'] = email;
    data['password'] = password;
    data['ticket_count'] = ticketCount;
    data['last_online'] = lastOnline;
    data['is_admin'] = isAdmin;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['dev_by'] = devBy;
    return data;
  }
}
